name: Continuous Integration

on:
  push:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        name: Build and Test
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup .NET Core
            uses: actions/setup-dotnet@v4

          - name: Restore
            run: |
                dotnet restore ./AikoLearning.sln
      
          - name: Build
            run: |          
                dotnet build --no-restore --configuration Release ./AikoLearning.sln
          
          - name: Test
            run: |                          
                dotnet test ./AikoLearning.sln --no-restore --no-build --configuration Release --logger trx --results-directory "TestResults"

          - uses: actions/upload-artifact@v4
            with:
                name: dotnet-test-results
                path: TestResults  