name: Continuous Integration

on:
  push:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    versioning:
        runs-on: ubuntu-latest
        name: Versioning
    
        outputs:
          version: ${{ steps.version.outputs.version }}
    
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
              ref: ${{ github.head_ref }}
              fetch-depth: 0 
          
          - uses:  codacy/git-version@2.8.3
            id: version
            with:
              release-branch: main
              prefix: v
    
          - name: Repository Tag
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              echo "::notice:: ${{ steps.version.outputs.version }}"
              git config --global user.email "${{ github.actor }}"@users.noreply.github.com
              git config --global user.name "${{ github.actor }}"
              git tag -a "${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
              git push --tags
            if: github.ref == 'refs/heads/main'
          
          - name: Create file version
            run: |
              echo ${{ steps.version.outputs.version }} > version.txt
            if: github.ref == 'refs/heads/main'
    
          - uses: actions/upload-artifact@v4
            with:
              name: version
              path: version.txt
            if: github.ref == 'refs/heads/main'

    build-and-test:
        runs-on: ubuntu-latest
        name: Build and Test
        needs: versioning
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup .NET Core
            uses: actions/setup-dotnet@v4

          - name: Restore
            run: |
                dotnet restore ./AikoLearning.sln
      
          - name: Build
            run: |          
                dotnet build --no-restore --configuration Release ./AikoLearning.sln
          
          - name: Test
            run: |                          
                dotnet test ./AikoLearning.sln --no-restore --no-build --configuration Release --logger trx --results-directory "TestResults"

          - uses: actions/upload-artifact@v4
            with:
                name: dotnet-test-results
                path: TestResults  

    horusec:
      runs-on: ubuntu-latest
      needs: versioning
      steps:
  
        # - name: Checkout repository
        #   uses: actions/checkout@v3
        #   with: 
        #     fetch-depth: 0
        - uses: actions/checkout@v4
        - name: Horusec
          env:
            DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
            DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
          # uses: fike/horusec-action@v0.2.2
          # with:
          #    arguments: -p=./ -e=false -o=sarif -O=./horusec_report.sarif
          # shell: bash
          run: |
  
            sudo apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu `lsb_release -cs` test"
            sudo apt update
            sudo apt install docker-ce
            sudo apt-cache madison docker-ce
            sudo apt-get install -y docker-ce=5:20.10.13~3-0~ubuntu-jammy -y --allow-downgrades
            sudo docker --version
            # docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
            
            curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
            mkdir reports
            horusec start -p="./" -o='sarif' -O='reports/horusec_report.sarif'
  
            # docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src/horusec horuszup/horusec-cli:latest horusec start -p /src/horusec -P $(pwd) -o='sarif' -O=/src/horusec/reports/horusec_report.sarif
        
        - name: Archive horusec report
          uses: actions/upload-artifact@v3
          with:
            name: horusec_report
            path: reports/horusec_report.sarif